# -*- mode: python ; coding: utf-8 -*-
version_file = 'G:/PycharmProjects/oldAssistant_v2/version.txt'

a = Analysis(
    ['main.py'],
    pathex=['G:/PycharmProjects/oldAssistant_v2'],
    binaries=[
        (r'G:\PycharmProjects\oldAssistant_v2\.venv\Lib\site-packages\vosk\libvosk.dll', 'vosk'),
        (r'G:\PycharmProjects\oldAssistant_v2\.venv\Lib\site-packages\vgamepad\win\vigem\client\x64\ViGEmClient.dll', 'vgamepad/win/vigem/client/x64')
    ],
    datas=[
        ('G:/PycharmProjects/oldAssistant_v2/app.manifest', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/version.txt', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/icon_assist.ico', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/logging_config.py', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/owl.svg', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/settings.json', 'user_settings'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/process_names.json', 'user_settings'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/color_settings.json', 'user_settings'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/commands.json', 'user_settings'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/links.json', 'user_settings'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/game_profiles_binds.json', 'user_settings'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/widget_state.json', 'user_settings'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/links for assist', 'user_settings/links for assist'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/presets', 'user_settings/presets'),
        ('G:/PycharmProjects/oldAssistant_v2/user_settings/screenshots', 'user_settings/screenshots'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/icons', 'bin/icons'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/utils.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/function_list_main.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/lists.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/OHM', 'bin/OHM'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/audio_control.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/init.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/check_update.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/apply_color_methods.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/speak_functions.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/speak_voice', 'bin/speak_voice'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/download_thread.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/model_ru', 'bin/model_ru'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/model_en', 'bin/model_en'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/commands_widgets.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/settings_widgets.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/other_options_widgets.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/widget_window.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/signals.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/toast_notification.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/toggle_mute_discord.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/choose_color_window.py', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/logo.svg', 'bin'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/color_presets', 'bin/color_presets'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/fonts', 'bin/fonts'),
        ('G:/PycharmProjects/oldAssistant_v2/bin/guides', 'bin/guides'),
        ('G:/PycharmProjects/oldAssistant_v2/config.ini', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/path_builder.py', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/Update.exe', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/swap-updater.exe', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/README.md', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/LICENSE.md', '.'),
        ('G:/PycharmProjects/oldAssistant_v2/THIRD-PARTY-LICENSES.md', '.'),
    ],
    hiddenimports=['vosk', 'pyaudio'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Assistant',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon_assist.ico'],
    manifest="G:/PycharmProjects/oldAssistant_v2/app.manifest",
    uac_admin=True,
    version=version_file,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Assistant',
)
